server.port=8080
spring.datasource.url=jdbc:hsqldb:file:db/yamsdb
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
